package App.Interpreter.Node;

public enum NodeKind {
  BLOCK,
  BOOLEAN_EXPRESSION,
  CLEAR_KEYWORD,
  COPY_KEYWORD,
  DECR_KEYWORD,
  DO_KEYWORD,
  END_KEYWORD,
  INCR_KEYWORD,
  INTEGER_IDENTIFIER,
  INTEGER_LITERAL,
  LINE_TERMINATOR,
  NOT_OPERATOR,
  TO_KEYWORD,
  WHILE_KEYWORD;

  public boolean isExpression() {
    return this == BOOLEAN_EXPRESSION;
  }
}
