package Interpreter.Node.Nodes;

public enum Nodes {
  BLOCK,
  BOOLEAN_EXPRESSION,
  CLEAR_KEYWORD,
  COPY_KEYWORD,
  DECR_KEYWORD,
  DO_KEYWORD,
  END_KEYWORD,
  INCR_KEYWORD,
  INTEGER_IDENTIFIER,
  INTEGER_LITERAL,
  LINE_TERMINATOR,
  NOT_OPERATOR,
  TO_KEYWORD,
  WHILE_KEYWORD,
}
